CREATE DATABASE IF NOT EXISTS bd_carrito;
CREATE DATABASE IF NOT EXISTS bd_facturacion;
CREATE DATABASE IF NOT EXISTS bd_inventario;
CREATE DATABASE IF NOT EXISTS bd_notificacion;
CREATE DATABASE IF NOT EXISTS bd_pago;
CREATE DATABASE IF NOT EXISTS bd_producto;
CREATE DATABASE IF NOT EXISTS bd_transporte;
CREATE DATABASE IF NOT EXISTS bd_usuario;